### ISSUE TITLE
no work in 1.0.1 version

### ISSUE THREAD

**Issue by benxshen** [Cardinal90/multi-cursor-case-preserve#1]
Thank you for providing this cool stuff to help replace string easily.
I found it worked when I first install on version 1.0.0, the version now is 1.0.1 but I found it doesn't work like before. I saw the change log for 1.0.1 "Now it doesn't changing anything, if case was equal in the first place - prevents some annoying false positives.", however, I am not clear what it changes about. 

How do I make it work?

**Comment by Cardinal90** [comment]
Damn, that was embarassing :). Please install 1.0.2, it should be fixed

**Comment by benxshen** [comment]
Many thanks :) 
It rocks again!!! Cool~
