### ISSUE TITLE
Undo requires 2x actions to undo.

### ISSUE THREAD

**Issue by BookOfGreg** [Cardinal90/multi-cursor-case-preserve#2]
This is mentioned in passing in the readme already (thanks!) but I think it's worth having an issue.

If you have this extension enabled and edit text with multiple case, you need to ctrl+z twice to undo the changes, and cannot redo more than one step.

**Comment by BookOfGreg** [comment]
I also want to say thanks, this is a very cool extension and one of the few things that I thought was missing from Sublime Text :D

**Comment by Cardinal90** [comment]
Thanks, I'm glad you like it!

Unfortunately I can't fix the problem without significant changes in VSCode. Here is an [issue](https://github.com/Microsoft/vscode/issues/38535) I opened, but it probably won't be fixed soon.

**Comment by Cardinal90** [comment]
Got annoyed by this and actually spent some time solving it. Still not perfect, but much better. Please check 1.0.3

**Comment by BookOfGreg** [comment]
Much better!
It handles undo and redo well enough now.

There's a slight issue with redo will put it in all-caps but if you undo it one more time then it becomes correct.

e.g.
```
Foo
foo
```
Highlight both, type 'bar'
Undo (to 'b'), Undo (to 'Foo/foo), Redo (to 'b'), Redo (ends as 'BAR/bar'), Undo (to 'Bar/bar')

But it's now good enough that it's a minor niggle and I no longer keep it disabled.
Thanks so much!
