### ISSUE TITLE
Need details on how to use it or activate it in documentation

### ISSUE THREAD

**Issue by Thomas0921** [Cardinal90/multi-cursor-case-preserve#3]
Hi Cardinal90, the multi-cursor-case-preserve is an awesome feature to have, but I couldn't find any detail on how to use it, or trigger it. any hotkey to press after highlighting the word?

Some details on it will be better :)

**Comment by Cardinal90** [comment]
Just select one word twice or more and start typing. It will trigger itself. If you mean, how to select the words, I think ctrl+D is the default hotkey.
