### ISSUE TITLE
How is this work?

### ISSUE THREAD

**Issue by PterPmnta** [Cardinal90/multi-cursor-case-preserve#8]
I'll try to implement this in my editor, but don't find a way to use it. I used multiples combinations but didn't work.

Alt + Click
Shift + Click
Ctrl + Click

Or whatever combinations of keys

Could you put the commands for the use of this extension?

**Comment by Cardinal90** [comment]
This extension doesn't provide any special commands. If you mean word selection as is shown in the gif in this repository's README, it is VSCode's keybinding for Add Selection For Next Find Match, I have it on Ctrl+D.

You could also select whole words using Alt + Double Click.

**Comment by PterPmnta** [comment]
> This extension doesn't provide any special commands. If you mean word selection as is shown in the gif in this repository's README, it is VSCode's keybinding for Add Selection For Next Find Match, I have it on Ctrl+D.
> 
> You could also select whole words using Alt + Double Click.

Thanks, men, work fine
