### ISSUE TITLE
problem using it

### ISSUE THREAD

**Issue by cristian-sima** [Cardinal90/multi-cursor-case-preserve#9]
![image](https://user-images.githubusercontent.com/12199042/154111056-fbbe9581-4255-4b7a-bafd-4d0b41325ad0.png)

**Comment by Cardinal90** [comment]
Hello. I'm afraid, I won't be able to help with this little info. Could you provide more? A file, where this happens, a sequence of steps which causes the error?

**Comment by cristian-sima** [comment]
1. Open VS
2. New file
3. The content of file 
```


Atom

Atom



atom 



A atom ATOM 


import {  } from "x25/";
```
Double click atom, type something. The extension did not work

**Comment by cristian-sima** [comment]
I have these extensions 

bradlc.vscode-tailwindcss
Cardinal90.multi-cursor-case-preserve
chrisbibby.hide-node-modules
christian-kohler.npm-intellisense    
chrmarti.regex
dbaeumer.vscode-eslint
dracula-theme.theme-dracula
eg2.vscode-npm-script
Floppie.pact
golang.go
hwencc.html-tag-wrapper
justusadam.language-haskell
marqu3s.aurora-x
michelemelluso.code-beautifier       
mrmlnc.vscode-duplicate
mrmlnc.vscode-scss
ms-python.python
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode.cpptools
PKief.material-icon-theme
richie5um2.vscode-sort-json
streetsidesoftware.code-spell-checker
vilicvane.sensitive-replace
zhuangtongfa.material-theme

**Comment by cristian-sima** [comment]
![image](https://user-images.githubusercontent.com/12199042/154494031-94970c06-bc2a-4bd6-a524-9538db99f429.png)

**Comment by Cardinal90** [comment]
> 1. Open VS
> 
> 2. New file
> 
> 3. The content of file
> 
> 
> ```
> 
> 
> Atom
> 
> Atom
> 
> 
> 
> atom 
> 
> 
> 
> A atom ATOM 
> 
> 
> import {  } from "x25/";
> ```
> 
> Double click atom, type something. The extension did not work

Are you sure, that's right? I mean, a double click only selects one instance of the word "atom". The extension won't even start to work with one cursor. Use ctrl+d a couple of times to select several instances of a word.

On the other hand, I managed to get that exception. It seems benign as it doesn't cause any actual problems for me, but I will investigate
